### ISSUE TITLE
TSteelworks does not like new railcraft

### ISSUE THREAD

**Issue by plaguewolf** [Ephys/TinkersSteelworks#105]
log: http://pastebin.com/sPbSque7

using:
railcraft 9.6.1.0
tsteelworks: 1.1.0-6

something borked, dunno in which it was, my guess is that railcraft has changed their fuel handler

relevant excerpt:
......
java.lang.ExceptionInInitializerError
        at toops.tsteelworks.common.plugins.mods.RailcraftPlugin.init(RailcraftPlugin.java:29) ~[RailcraftPlugin.class:1.7.10-1.1.0-6]
        at toops.tsteelworks.common.plugins.PluginController.init(PluginController.java:19) ~[PluginController.class:1.7.10-1.1.0-6]
        at toops.tsteelworks.TSteelworks.init(TSteelworks.java:77) ~[TSteelworks.class:1.7.10-1.1.0-6]

......

Caused by: java.lang.RuntimeException: Could not fetch class for interface toops.tsteelworks.api.highoven.IFuelRegistry

**Comment by plaguewolf** [comment]
further testing reveals that tsteelworks dev version 1.1.0-16 works fine with latest railcraft. XD

didnt think to try the dev version.
